### ISSUE TITLE
Support for averaging and sample time register

### ISSUE THREAD

**Issue by jeremiahrose** [adafruit/Adafruit_CircuitPython_CAP1188#16]
I'm trying to prototype a musical application with the CAP1188 but the latency on a touch is slightly too long at the default setting. It would be good if the library provided getters and setters for the "AVERAGING AND SAMPLING CONFIGURATION REGISTER" so that the sample time can be adjusted or reduced.

**Comment by jposada202020** [comment]
@jeremiahrose is this something that you are still using? I do not have this particular hardware to test the code changes...
Could you submit a PR, if not, If I do the coding could you test it in your CAP1188?
Let me know thanks :)

**Comment by jeremiahrose** [comment]
Hey all,
This was working perfectly on my CAP1188 when I submitted the pull request in Jul 2020. Not sure why it wasn't accepted. Am no longer using the device so can't contribute any further now
