### ISSUE TITLE
Changing default i2c address

### ISSUE THREAD

**Issue by Devanshi1510** [adafruit/Adafruit_CircuitPython_CAP1188#9]
Hi, 
Is there any option to change the default i2c addresss which is 0x29h to 0x28h ? I changed it in i2c.py file but it somehow didnt worked. 

Hoping to get reply soon.
Thanks.

**Comment by caternuson** [comment]
Yep. You set the different address via the `AD` pin. See here for details:
https://learn.adafruit.com/adafruit-cap1188-breakout/wiring
And then you can override the default address and pass in the new one when you create your `CAP1188_I2C` object, like this:
```python
cap = CAP1188_I2C(i2c, address=0x28)
```

**Comment by Devanshi15** [comment]
Thanks, I got it working!!!
